### ISSUE TITLE
[PE-D][Tester E] Unexpected statements are printed upon adding of a question

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#63] opened 2023-04-01 00:08 UTC
When a question is added, the user is able to see the logger messages too. Such behaviour was not mentioned in the UG.

![2113_ped_logger.PNG](https://raw.githubusercontent.com/ysl-28/ped/main/files/f92e5941-b0a8-4f24-9a8a-84ea820dedf4.PNG)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ysl-28/ped#1

**Comment by joulev** [comment] 2023-04-01 03:13
Duplicate of #62.

**Closed as completed by joulev** 2023-04-01 03:13 UTC
