### ISSUE TITLE
[PE-D][Tester D] Invalid update command for given command format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#83] opened 2023-04-01 01:06 UTC
## Describe the bug
Based on what is given in the user guide, to update command, the format is `update /q QUERY`, however, this will be regarded as an invalid command

![image.png](https://raw.githubusercontent.com/wenxin-c/ped/main/files/ee36625c-64ff-4f02-9360-eac1a1818c7c.png)

## To Reproduce
1. Launch program
2. Input `add /a test /q test`
3. Input `update /q test`

## Expected outcome
For step 4, the list of questions containing `test` should be displayed

##Actual outcome:
For step 4, the command is regarded as invalid

## Screenshots

![image.png](https://raw.githubusercontent.com/wenxin-c/ped/main/files/951f5905-f24d-4d64-a3a2-163d8de86636.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wenxin-c/ped#4

**Comment by joulev** [comment] 2023-04-01 03:32
Duplicate of #41.

**Closed as completed by joulev** 2023-04-01 03:32 UTC
