### ISSUE TITLE
[PE-D][Tester E] Unable to delete cards

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T15-4/tp#96] opened 2023-04-01 01:45 UTC
The command for deleting cards based on their query does not seem to work. 

![2113_ped_cannot_delete.PNG](https://raw.githubusercontent.com/ysl-28/ped/main/files/c2b76df0-7d68-4683-a743-91b169ba6c96.PNG)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: ysl-28/ped#5

**Comment by joulev** [comment] 2023-04-01 03:39
Duplicate of #89.

**Closed as completed by joulev** 2023-04-01 03:39 UTC
