### ISSUE TITLE
[PE-D][Tester D] Ambiguity of command other than y or n

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T15-4/tp#114] opened 2023-04-01 02:10 UTC
## Describe the bug
When being asked "Did you get it right", if the answer is something other than y/n, it will show that the command is invalid and bypass this question. However, based on the user guide, inputs other than y will cause a particular question to queue up for review again. If `n` is input, the question will queue immediately, but if a command other than y/n is input, this question will be bypassed and only appear when input `review` again. This cause confusion and can be improved by better differentiating `y`, `n` and other commands. 

## To Reproduce
1. Launch program
2. Input `add /q test /a test `
3. Input `review`
4. Input `test` for the question `Did you get it right?`

## Expected behavior
The question will be queued up for review again immedately based on the behaviour for `n` and user guide

## Actual output
This question will be bypassed and not queued up for review immediately

## Screenshots

![image.png](https://raw.githubusercontent.com/wenxin-c/ped/main/files/780d96ab-d53d-435c-a224-ae6a7c3cc6df.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: wenxin-c/ped#13

**Comment by joulev** [comment] 2023-04-01 03:50
Duplicate of #65.

**Closed as completed by joulev** 2023-04-01 03:50 UTC
